title: Badrumsrenovering Stockholm
email: hej@stockholmsbadrumsrenovering.com
description: KM Living är ett byggföretag i Stockholm. Vi är experter på badrumsrenovering, köksrenovering, totalrenovering mm. Kontakta oss nu för en gratis offert!
baseurl: ""
url: "https://www.stockholmsbadrumsrenovering.com"
# AMP
amp_cache_url: stockholmsbadrumsrenovering.com

# Images
og_image: /images/stockholmsbadrumsrenovering.jpg
icon_towel: /images/icons/towel.svg

# Schema
organization_name: Stockholms Badrumsrenovering

collections:
  posts:
    permalink: /bloggen/:year/:title
  kunder:
    output: true
    permalink: /kunder/:path/
  rekommendationer:
    output: true
    permalink: /rekommendationer/:path/
  campaigns:
    output: true
    permalink: /kampanjer/:path/

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude: [Rakefile]