title: Badrumsrenovering Stockholm
email: hej@stockholmsbadrumsrenovering.com
description: KM Living är ett byggföretag i Stockholm. Vi är experter på badrumsrenovering, köksrenovering, totalrenovering mm. Kontakta oss nu för en gratis offert!
baseurl: ""
url: "https://www.stockholmsbadrumsrenovering.com"
# AMP
amp_cache_url: stockholmsbadrumsrenovering.com

# Images
og_image: https://res.cloudinary.com/stockholmsbadrumsrenovering/image/upload/c_scale,w_664/v1475944995/main/stockholmsbadrumsrenovering.jpg
logo_jpg: https://res.cloudinary.com/stockholmsbadrumsrenovering/image/upload/v1475945656/main/logo.jpg
icon_towel: https://res.cloudinary.com/stockholmsbadrumsrenovering/image/upload/v1475946698/icons/towel.svg

# Schema
organization_name: Stockholms Badrumsrenovering

collections:
  posts:
    permalink: /bloggen/:year/:title
  badrumsrenovering:
    output: true
    permalink: /:path/
  rekommendationer:
    output: true
    permalink: /rekommendationer/:path/
  campaigns:
    output: true
    permalink: /kampanjer/:path/

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude: [Rakefile]