# Schema
organization_name: Stockholms Badrumsrenovering
title: Badrumsrenovering Stockholm
email: hej@stockholmsbadrumsrenovering.com
description: KM Living är ett byggföretag i Stockholm. Vi är experter på badrumsrenovering, köksrenovering, totalrenovering mm. Kontakta oss nu för en gratis offert!
baseurl: ""
url: "https://www.stockholmsbadrumsrenovering.com"
phone: "08-36 61 21"
address: "Erik Sandbergs gata 6"
postalcode: "16934"
city: "Solna"
country: "Sweden"
service_type: "Badrumsrenovering"
area_served: "Stockholm"

# AMP
amp_cache_url: stockholmsbadrumsrenovering.com

# Images
og_image: https://res.cloudinary.com/stockholmsbadrumsrenovering/image/upload/c_scale,w_664/v1475944995/main/stockholmsbadrumsrenovering.jpg
logo_jpg: https://res.cloudinary.com/stockholmsbadrumsrenovering/image/upload/v1475945656/main/logo.jpg
icon_towel: https://res.cloudinary.com/stockholmsbadrumsrenovering/image/upload/v1475946698/icons/towel.svg

# Collections
collections:
  posts:
    permalink: /bloggen/:year/:title
  badrumsrenovering:
    output: true
    permalink: /:path/
  rekommendationer:
    output: true
    permalink: /rekommendationer/:path/
  campaigns:
    output: true
    permalink: /kampanjer/:path/

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-admin

exclude: [Rakefile]